// <auto-generated />
using DataServices;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataServices.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250512131605_SeedUsers")]
    partial class SeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataServices.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@dto.com",
                            IsAdmin = true,
                            Name = "Admin",
                            Password = "$2a$11$Aee9b5mUX9sqI0oRxQeFuuIZPmK8tOSXttqWW/0CTyvnBqxIi4ch2"
                        },
                        new
                        {
                            Id = 2,
                            Email = "daniel@dto.com",
                            IsAdmin = false,
                            Name = "Daniel",
                            Password = "$2a$11$FMc3Rhe6JZacxu/VIUGNMOGK1HhH21OlgTSYQ7O1RWy1LjzB1Tt8W"
                        },
                        new
                        {
                            Id = 3,
                            Email = "hector@dto.com",
                            IsAdmin = false,
                            Name = "Hector",
                            Password = "$2a$11$uY3qXlcB55QzSnj/q/ya/.3MhN9vhQWSUp4sZ1C67DPyEb/MUITZ."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
